name: Run Selenium Java
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run test
        run: mvn test -Dtest.suite=src/test/resources/testplan/bmi-testplan.xml
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1